[package]
name = "bevy_spatial_egui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", default-features = false }
bevy_egui = { version = "0.32", feature = ["render"] }
bevy-suis = {git = "https://github.com/MiniMinerX/bevy-suis.git", branch = "dev-0.15-p3"}
wgpu-types = { version = "23.0"}

[dev-dependencies]
bevy_panorbit_camera = "0.22"
bevy_mod_openxr = { git = "https://github.com/awtterpip/bevy_oxr.git"}
bevy_xr_utils = { git = "https://github.com/awtterpip/bevy_oxr.git"}

[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"
