[package]
name = "bevy_spatial_egui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.16"
bevy_egui = "0.34.1"
bevy-suis = { git = "https://github.com/Schmarni-Dev/bevy-suis", default-features = false }

[dev-dependencies]
bevy_panorbit_camera = "0.26"
bevy_mod_openxr = "0.3"
bevy_mod_xr = "0.3"

[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"
